version: "3.9"
services:
    proxy:
        image: owasp/modsecurity:3-nginx
        ports:
            - "80:80"
        depends_on: 
            - web
        volumes:
            - $PWD/etc/modsecurity:/etc/modsecurity
            - $PWD/etc/modsecurity.d/include.conf:/etc/modsecurity.d/include.conf
            - $PWD/etc/modsecurity.d/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf
            - $PWD/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - $PWD/modsec_audit.log:/var/log/modsec_audit.log

    web: 
        image: vulnerables/web-dvwa
        ports:
            - 8000:80