name: "DefectDojo CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  modsecurity-ubuntu-latest-job:
    name: "modsecurity docker  images  ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "ubuntu" 
      version: "latest"
      name: "ubuntu2104/apache2"
      dockerfilename: "Dockerfile.ubuntu.modsecurity"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch         
    - name: "docker build apache2 base"
      run: |
        # https://github.com/DefectDojo/django-DefectDojo
        git clone https://github.com/DefectDojo/django-DefectDojo
        cd django-DefectDojo
        # building
        ./dc-build.sh 
        # running (for other profiles besides mysql-rabbitmq look at https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/DOCKER.md)
        ./dc-up.sh mysql-rabbitmq
        # obtain admin credentials. the initializer can take up to 3 minutes to run
        # use docker-compose logs -f initializer to track progress
        docker-compose logs initializer | grep "Admin password:"        


